spring:
  main:
    allow-bean-definition-overriding: true

ldes-server:
  host-name: "http://localhost:8080"
  collections:
      collection-name: "parcels"
      member-type: "https://basisregisters.vlaanderen.be/implementatiemodel/gebouwenregister#Perceel"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
      version-of: "http://purl.org/dc/terms/isVersionOf"
      views:
        - name: "by-page"
          fragmentations:
            - name: "pagination"
              config:
                memberLimit: 100

# Prevents error of tracing endpoint not found
management:
  tracing:
    enabled: false
