spring:
  main:
    allow-bean-definition-overriding: true

# Prevents error of tracing endpoint not found
ldes-server:
  host-name: "http://localhost:8080"
  collections:
    - member-type: "https://basisregisters.vlaanderen.be/implementatiemodel/gebouwenregister#Perceel"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
      version-of: "http://purl.org/dc/terms/isVersionOf"
      collection-name: "parcels"
      views:
        - name: "by-page"
          fragmentations:
            - name: "pagination"
              config:
                memberLimit: 100
    - collection-name: "building-units"
      member-type: "https://data.vlaanderen.be/ns/gebouw#Gebouweenheid"
      timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
      views:
        - name: "by-other-page"
          fragmentations:
            - name: "pagination"
              config:
                memberLimit: 1
        - name: "by-page"
          fragmentations:
            - name: "pagination"
              config:
                memberLimit: 5
management:
  tracing:
    enabled: false

