#name: Add forks and dependabot PRs to project
#
#on:
#  pull_request_target:
#    types:
#      - opened
#      - reopened
#
#jobs:
#  add-to-project:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/add-to-project@v0.4.0
#        if: ${{ github.event.pull_request.head.repo.full_name != 'Informatievlaanderen/VSDS-LDESServer4J' || github.actor == 'dependabot[bot]' }}
#        with:
#          project-url: https://github.com/orgs/Informatievlaanderen/projects/4
#          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}